"""
Toxic Backlink Audit & Google Search Console Disavow File Generator.
Scans URLs / domains for toxic footprints (spam TLDs, PBN patterns, unnatural anchors) and exports disavow.txt files.
"""

from pathlib import Path
from typing import Dict, Any, List, Tuple


class DisavowGenerator:
    """Scans toxic links and exports disavow.txt files for Google Search Console."""

    SPAM_TLDS = {".xyz", ".top", ".gq", ".cf", ".tk", ".ml", ".ga", ".work", ".click", ".loan", ".racing", ".fit", ".icu"}
    SPAM_KEYWORDS = {"casino", "poker", "payday", "loans", "replica", "viagra", "rx", "gambling", "crypto", "hack"}

    @classmethod
    def audit_url_list(cls, urls: List[str]) -> Tuple[List[Dict[str, Any]], List[str]]:
        """
        Audits a list of URLs or domains, flagging toxic links and returning disavow lines.
        """
        audit_results = []
        disavow_lines = [
            "# Google Search Console Disavow File",
            "# Generated by PythonAiWriter Technical SEO Suite",
            ""
        ]

        disavowed_domains = set()

        for raw_url in urls:
            url = raw_url.strip()
            if not url:
                continue

            clean_url = url.replace("http://", "").replace("https://", "").split("/")[0].lower()
            tld = f".{clean_url.split('.')[-1]}" if "." in clean_url else ""

            is_toxic = False
            reasons = []

            if tld in cls.SPAM_TLDS:
                is_toxic = True
                reasons.append(f"Spam TLD ({tld})")

            for kw in cls.SPAM_KEYWORDS:
                if kw in clean_url:
                    is_toxic = True
                    reasons.append(f"Spam keyword in domain ('{kw}')")
                    break

            if len(clean_url) > 45:
                is_toxic = True
                reasons.append("Unnaturally long domain name")

            audit_results.append({
                "domain": clean_url,
                "is_toxic": is_toxic,
                "reasons": reasons if is_toxic else ["Clean Domain"]
            })

            if is_toxic and clean_url not in disavowed_domains:
                disavowed_domains.add(clean_url)
                disavow_lines.append(f"domain:{clean_url}")

        return audit_results, disavow_lines

    @classmethod
    def export_disavow_file(cls, disavow_lines: List[str], output_path: Path) -> Path:
        """Writes disavow lines to a disavow.txt file."""
        output_path.write_text("\n".join(disavow_lines), encoding="utf-8")
        return output_path
